version: '3.8'

services:
  api:
    build: .
    container_name: ai-debate-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
